Update pr-nctl-scan.yml
Add check for dockerfile

diff --git a/.github/workflows/pr-nctl-scan.yml b/.github/workflows/pr-nctl-scan.yml
--- a/.github/workflows/pr-nctl-scan.yml
+++ b/.github/workflows/pr-nctl-scan.yml
@@ -28,11 +28,18 @@ jobs:
           repository: nirmata/cci-policies
           path: './cci-policies'
 
-      - name: Install Nirmata CLI
-        run: |
-          curl -O -L -s https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_3.3.7/nctl_3.3.7_linux_64-bit.zip
-          unzip *.zip
-          ls -lR ./cci-policies
+#      - name: Install Nirmata CLI
+#        run: |
+#          curl -O -L -s https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_3.3.7/nctl_3.3.7_linux_64-bit.zip
+#          unzip *.zip
+#         ls -lR ./cci-policies
+      - name: Copy a file from s3
+        uses: prewk/s3-cp-action@v2
+        with:
+          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          source: 's3://nctl-cci-demo/nctl'
+          dest: './nctl'
 
       - name: Check nctl install
         run: ./nctl version
@@ -40,12 +47,15 @@ jobs:
       - name: Validate manifests
         run: |
           ./nctl scan --policies ./cci-policies/policies --resource=./nginx -e
-          ./nctl scan --policies ./cci-policies/policies --resource=./nginx -f json -o temp.json
-          FAIL_COUNT=$(cat ./temp.json |jq '.OverallSummary.Fail')
-          echo $FAIL_COUNT
-          if [[ $FAIL_COUNT == "0" ]]; then
-            echo "No errors found"
-          else
-            echo "$FAIL_COUNT errors found"
-            exit 1
-          fi
+#          ./nctl scan --policies ./cci-policies/policies --resource=./nginx -f json -o temp.json
+#          FAIL_COUNT=$(cat ./temp.json |jq '.OverallSummary.Fail')
+#          echo $FAIL_COUNT
+#          if [[ $FAIL_COUNT == "0" ]]; then
+#            echo "No errors found"
+#          else
+#            echo "$FAIL_COUNT errors found"
+#            exit 1
+#          fi
+      - name: Validate dockerfile
+        run: |
+          ./nctl scan --policies ./cci-policies/docker-policies --resource=./docker/Dockerfile --resource-type dockerfile -e
