Update pr-nctl-scan.yml
Add checks

diff --git a/.github/workflows/pr-nctl-scan.yml b/.github/workflows/pr-nctl-scan.yml
--- a/.github/workflows/pr-nctl-scan.yml
+++ b/.github/workflows/pr-nctl-scan.yml
@@ -40,3 +40,12 @@ jobs:
       - name: Validate manifests
         run: |
           ./nctl scan --policies ./cci-policies/policies --resource=./nginx -e
+          ./nctl scan --policies ./cci-policies/policies --resource=./nginx -f json -o temp.json
+          FAIL_COUNT=$(cat ./temp.json |jq '.OverallSummary')
+          echo $FAIL_COUNT
+          if [[$FAIL_COUNT == "0"]]; then
+            echo "No errors found"
+          else
+            echo "$FAIL_COUNT errors found"
+            exit 1
+          fi
